### ISSUE TITLE
TypeError with --streaming-mode flag

### ISSUE THREAD

**Issue by HeikoVater** [daswer123/xtts-api-server#19]
If I run  `python -m xtts_api_server --streaming-mode` I get the following error:

> 2023-12-13 00:07:58.526 | WARNING  | xtts_api_server.server:<module>:53 - 'Streaming Mode' has certain limitations, you can read about them here https://github.com/daswer123/xtts-api-server#about-streaming-mode
2023-12-13 00:07:58.526 | INFO     | xtts_api_server.server:<module>:58 - Load model for Streaming
Using model: xtts
ERROR:root:Error initializing main coqui engine model: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/naa/git/XTTSv2/venv/lib/python3.11/site-packages/xtts_api_server/RealtimeTTS/engines/coqui_engine.py", line 227, in _synthesize_worker
    tts.load_checkpoint(
  File "/home/naa/git/XTTSv2/venv/lib/python3.11/site-packages/TTS/tts/models/xtts.py", line 759, in load_checkpoint
    speaker_file_path = speaker_file_path or os.path.join(checkpoint_dir, "speakers_xtts.pth")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/naa/git/XTTSv2/venv/lib/python3.11/site-packages/xtts_api_server/RealtimeTTS/engines/coqui_engine.py", line 227, in _synthesize_worker
    tts.load_checkpoint(
  File "/home/naa/git/XTTSv2/venv/lib/python3.11/site-packages/TTS/tts/models/xtts.py", line 759, in load_checkpoint
    speaker_file_path = speaker_file_path or os.path.join(checkpoint_dir, "speakers_xtts.pth")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

It works fine without the `--streaming-mode` flag.

I installed it via

> pip install xtts-api-server
> pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118

but had to run `pip install pydub` as well, since it was missing.

The version of `xtts-api-server` installed is `0.6.2`. I am on Linux.

**Comment by daswer123** [comment]
Hi, thanks for letting me know.
The problem has been detected and fixed, everything should work now.
